### model
model_name_or_path: Qwen/Qwen2.5-VL-7B-Instruct
image_max_pixels: 2007040
video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: true
freeze_multi_modal_projector: true
freeze_language_model: false
deepspeed: examples/deepspeed/ds_z3_config.json
use_deqa_loss: true  # 启用DEQA loss

### dataset
dataset: diqa_color_pair # 使用DIQA数据集
template: qwen2_vl
cutoff_len: 4096
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: output_path
logging_steps: 10
save_steps: 50000
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: tensorboard  # 使用tensorboard记录训练过程

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 2  # 使用DeepSpeed时可以减小梯度累积步数
learning_rate: 2.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.03
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

## eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
